#!/bin/bash
# Image Optimization Script
# Generated automatically

echo "🖼️  Starting image optimization..."

# Check if required tools are installed
if ! command -v cwebp &> /dev/null; then
    echo "❌ cwebp not found. Please install WebP tools:"
    echo "   macOS: brew install webp"
    echo "   Ubuntu: sudo apt-get install webp"
    exit 1
fi

if ! command -v avifenc &> /dev/null; then
    echo "⚠️  avifenc not found. AVIF conversion will be skipped."
    echo "   Install: npm install -g @squoosh/cli"
fi

# Create output directory
mkdir -p "./images/optimized"

# Execute optimization commands
cwebp -q 85 "images/Pawfect.png" -o "images/optimized/Pawfect.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/Pawfect.png" "images/optimized/Pawfect.avif"
cwebp -q 85 -resize 300 0 "images/Pawfect.png" -o "images/optimized/Pawfect-small.webp"
cwebp -q 85 -resize 600 0 "images/Pawfect.png" -o "images/optimized/Pawfect-medium.webp"
cwebp -q 85 -resize 1200 0 "images/Pawfect.png" -o "images/optimized/Pawfect-large.webp"
cwebp -q 85 "images/background-image-hero.png" -o "images/optimized/background-image-hero.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/background-image-hero.png" "images/optimized/background-image-hero.avif"
cwebp -q 85 -resize 300 0 "images/background-image-hero.png" -o "images/optimized/background-image-hero-small.webp"
cwebp -q 85 -resize 600 0 "images/background-image-hero.png" -o "images/optimized/background-image-hero-medium.webp"
cwebp -q 85 -resize 1200 0 "images/background-image-hero.png" -o "images/optimized/background-image-hero-large.webp"
cwebp -q 85 "images/categorysectionpuppy.png" -o "images/optimized/categorysectionpuppy.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/categorysectionpuppy.png" "images/optimized/categorysectionpuppy.avif"
cwebp -q 85 -resize 300 0 "images/categorysectionpuppy.png" -o "images/optimized/categorysectionpuppy-small.webp"
cwebp -q 85 -resize 600 0 "images/categorysectionpuppy.png" -o "images/optimized/categorysectionpuppy-medium.webp"
cwebp -q 85 -resize 1200 0 "images/categorysectionpuppy.png" -o "images/optimized/categorysectionpuppy-large.webp"
cwebp -q 85 "images/category-cat-playing-with-toy.png" -o "images/optimized/category-cat-playing-with-toy.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/category-cat-playing-with-toy.png" "images/optimized/category-cat-playing-with-toy.avif"
cwebp -q 85 -resize 300 0 "images/category-cat-playing-with-toy.png" -o "images/optimized/category-cat-playing-with-toy-small.webp"
cwebp -q 85 -resize 600 0 "images/category-cat-playing-with-toy.png" -o "images/optimized/category-cat-playing-with-toy-medium.webp"
cwebp -q 85 -resize 1200 0 "images/category-cat-playing-with-toy.png" -o "images/optimized/category-cat-playing-with-toy-large.webp"
cwebp -q 85 "images/dogfood-BLOG-INDEX.PNG" -o "images/optimized/dogfood-BLOG-INDEX.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/dogfood-BLOG-INDEX.PNG" "images/optimized/dogfood-BLOG-INDEX.avif"
cwebp -q 85 -resize 300 0 "images/dogfood-BLOG-INDEX.PNG" -o "images/optimized/dogfood-BLOG-INDEX-small.webp"
cwebp -q 85 -resize 600 0 "images/dogfood-BLOG-INDEX.PNG" -o "images/optimized/dogfood-BLOG-INDEX-medium.webp"
cwebp -q 85 -resize 1200 0 "images/dogfood-BLOG-INDEX.PNG" -o "images/optimized/dogfood-BLOG-INDEX-large.webp"
cwebp -q 85 "images/Cat-for-blog.png" -o "images/optimized/Cat-for-blog.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/Cat-for-blog.png" "images/optimized/Cat-for-blog.avif"
cwebp -q 85 -resize 300 0 "images/Cat-for-blog.png" -o "images/optimized/Cat-for-blog-small.webp"
cwebp -q 85 -resize 600 0 "images/Cat-for-blog.png" -o "images/optimized/Cat-for-blog-medium.webp"
cwebp -q 85 -resize 1200 0 "images/Cat-for-blog.png" -o "images/optimized/Cat-for-blog-large.webp"
cwebp -q 85 "images/grooming-acessories.png" -o "images/optimized/grooming-acessories.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/grooming-acessories.png" "images/optimized/grooming-acessories.avif"
cwebp -q 85 -resize 300 0 "images/grooming-acessories.png" -o "images/optimized/grooming-acessories-small.webp"
cwebp -q 85 -resize 600 0 "images/grooming-acessories.png" -o "images/optimized/grooming-acessories-medium.webp"
cwebp -q 85 -resize 1200 0 "images/grooming-acessories.png" -o "images/optimized/grooming-acessories-large.webp"
cwebp -q 85 "images/dog-food.png" -o "images/optimized/dog-food.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/dog-food.png" "images/optimized/dog-food.avif"
cwebp -q 85 -resize 300 0 "images/dog-food.png" -o "images/optimized/dog-food-small.webp"
cwebp -q 85 -resize 600 0 "images/dog-food.png" -o "images/optimized/dog-food-medium.webp"
cwebp -q 85 -resize 1200 0 "images/dog-food.png" -o "images/optimized/dog-food-large.webp"
cwebp -q 85 "images/dog-toy.png" -o "images/optimized/dog-toy.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/dog-toy.png" "images/optimized/dog-toy.avif"
cwebp -q 85 -resize 300 0 "images/dog-toy.png" -o "images/optimized/dog-toy-small.webp"
cwebp -q 85 -resize 600 0 "images/dog-toy.png" -o "images/optimized/dog-toy-medium.webp"
cwebp -q 85 -resize 1200 0 "images/dog-toy.png" -o "images/optimized/dog-toy-large.webp"
cwebp -q 85 "images/dog-bed.png" -o "images/optimized/dog-bed.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/dog-bed.png" "images/optimized/dog-bed.avif"
cwebp -q 85 -resize 300 0 "images/dog-bed.png" -o "images/optimized/dog-bed-small.webp"
cwebp -q 85 -resize 600 0 "images/dog-bed.png" -o "images/optimized/dog-bed-medium.webp"
cwebp -q 85 -resize 1200 0 "images/dog-bed.png" -o "images/optimized/dog-bed-large.webp"
cwebp -q 85 "images/cat-toy.png" -o "images/optimized/cat-toy.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/cat-toy.png" "images/optimized/cat-toy.avif"
cwebp -q 85 -resize 300 0 "images/cat-toy.png" -o "images/optimized/cat-toy-small.webp"
cwebp -q 85 -resize 600 0 "images/cat-toy.png" -o "images/optimized/cat-toy-medium.webp"
cwebp -q 85 -resize 1200 0 "images/cat-toy.png" -o "images/optimized/cat-toy-large.webp"
cwebp -q 85 "images/cat-tree.png" -o "images/optimized/cat-tree.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/cat-tree.png" "images/optimized/cat-tree.avif"
cwebp -q 85 -resize 300 0 "images/cat-tree.png" -o "images/optimized/cat-tree-small.webp"
cwebp -q 85 -resize 600 0 "images/cat-tree.png" -o "images/optimized/cat-tree-medium.webp"
cwebp -q 85 -resize 1200 0 "images/cat-tree.png" -o "images/optimized/cat-tree-large.webp"
cwebp -q 85 "images/cat-food.png" -o "images/optimized/cat-food.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/cat-food.png" "images/optimized/cat-food.avif"
cwebp -q 85 -resize 300 0 "images/cat-food.png" -o "images/optimized/cat-food-small.webp"
cwebp -q 85 -resize 600 0 "images/cat-food.png" -o "images/optimized/cat-food-medium.webp"
cwebp -q 85 -resize 1200 0 "images/cat-food.png" -o "images/optimized/cat-food-large.webp"
cwebp -q 85 "images/dog-bed-BLOG-INDEX.PNG" -o "images/optimized/dog-bed-BLOG-INDEX.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/dog-bed-BLOG-INDEX.PNG" "images/optimized/dog-bed-BLOG-INDEX.avif"
cwebp -q 85 -resize 300 0 "images/dog-bed-BLOG-INDEX.PNG" -o "images/optimized/dog-bed-BLOG-INDEX-small.webp"
cwebp -q 85 -resize 600 0 "images/dog-bed-BLOG-INDEX.PNG" -o "images/optimized/dog-bed-BLOG-INDEX-medium.webp"
cwebp -q 85 -resize 1200 0 "images/dog-bed-BLOG-INDEX.PNG" -o "images/optimized/dog-bed-BLOG-INDEX-large.webp"
cwebp -q 85 "images/cat-bed-BLOG-INDEX.PNG" -o "images/optimized/cat-bed-BLOG-INDEX.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/cat-bed-BLOG-INDEX.PNG" "images/optimized/cat-bed-BLOG-INDEX.avif"
cwebp -q 85 -resize 300 0 "images/cat-bed-BLOG-INDEX.PNG" -o "images/optimized/cat-bed-BLOG-INDEX-small.webp"
cwebp -q 85 -resize 600 0 "images/cat-bed-BLOG-INDEX.PNG" -o "images/optimized/cat-bed-BLOG-INDEX-medium.webp"
cwebp -q 85 -resize 1200 0 "images/cat-bed-BLOG-INDEX.PNG" -o "images/optimized/cat-bed-BLOG-INDEX-large.webp"
cwebp -q 85 "images/pet-health-BLOG-INDEX.PNG" -o "images/optimized/pet-health-BLOG-INDEX.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/pet-health-BLOG-INDEX.PNG" "images/optimized/pet-health-BLOG-INDEX.avif"
cwebp -q 85 -resize 300 0 "images/pet-health-BLOG-INDEX.PNG" -o "images/optimized/pet-health-BLOG-INDEX-small.webp"
cwebp -q 85 -resize 600 0 "images/pet-health-BLOG-INDEX.PNG" -o "images/optimized/pet-health-BLOG-INDEX-medium.webp"
cwebp -q 85 -resize 1200 0 "images/pet-health-BLOG-INDEX.PNG" -o "images/optimized/pet-health-BLOG-INDEX-large.webp"
cwebp -q 85 "images/Cat-dog-grooming-BLOG.png" -o "images/optimized/Cat-dog-grooming-BLOG.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/Cat-dog-grooming-BLOG.png" "images/optimized/Cat-dog-grooming-BLOG.avif"
cwebp -q 85 -resize 300 0 "images/Cat-dog-grooming-BLOG.png" -o "images/optimized/Cat-dog-grooming-BLOG-small.webp"
cwebp -q 85 -resize 600 0 "images/Cat-dog-grooming-BLOG.png" -o "images/optimized/Cat-dog-grooming-BLOG-medium.webp"
cwebp -q 85 -resize 1200 0 "images/Cat-dog-grooming-BLOG.png" -o "images/optimized/Cat-dog-grooming-BLOG-large.webp"
cwebp -q 85 "images/cat-for-BLOG-INDEX.PNG" -o "images/optimized/cat-for-BLOG-INDEX.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/cat-for-BLOG-INDEX.PNG" "images/optimized/cat-for-BLOG-INDEX.avif"
cwebp -q 85 -resize 300 0 "images/cat-for-BLOG-INDEX.PNG" -o "images/optimized/cat-for-BLOG-INDEX-small.webp"
cwebp -q 85 -resize 600 0 "images/cat-for-BLOG-INDEX.PNG" -o "images/optimized/cat-for-BLOG-INDEX-medium.webp"
cwebp -q 85 -resize 1200 0 "images/cat-for-BLOG-INDEX.PNG" -o "images/optimized/cat-for-BLOG-INDEX-large.webp"
cwebp -q 85 "images/brown-cat-dog-together-looking-600nw-2198514787.png" -o "images/optimized/brown-cat-dog-together-looking-600nw-2198514787.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/brown-cat-dog-together-looking-600nw-2198514787.png" "images/optimized/brown-cat-dog-together-looking-600nw-2198514787.avif"
cwebp -q 85 -resize 300 0 "images/brown-cat-dog-together-looking-600nw-2198514787.png" -o "images/optimized/brown-cat-dog-together-looking-600nw-2198514787-small.webp"
cwebp -q 85 -resize 600 0 "images/brown-cat-dog-together-looking-600nw-2198514787.png" -o "images/optimized/brown-cat-dog-together-looking-600nw-2198514787-medium.webp"
cwebp -q 85 -resize 1200 0 "images/brown-cat-dog-together-looking-600nw-2198514787.png" -o "images/optimized/brown-cat-dog-together-looking-600nw-2198514787-large.webp"
cwebp -q 85 "images/Deals-Background-img.png" -o "images/optimized/Deals-Background-img.webp"
avifenc --min 0 --max 63 --speed 4 --yuv 420 --q 80 "images/Deals-Background-img.png" "images/optimized/Deals-Background-img.avif"
cwebp -q 85 -resize 300 0 "images/Deals-Background-img.png" -o "images/optimized/Deals-Background-img-small.webp"
cwebp -q 85 -resize 600 0 "images/Deals-Background-img.png" -o "images/optimized/Deals-Background-img-medium.webp"
cwebp -q 85 -resize 1200 0 "images/Deals-Background-img.png" -o "images/optimized/Deals-Background-img-large.webp"

echo "✅ Image optimization complete!"
echo "📁 Optimized images saved to: ./images/optimized"
